# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0542c24d8d4561e06f8633fabba3669e79073da4398056dc4a7529755a6c2066f222431df0400bc115dd63918167f2d03303631d93aa7c4e0ff7b87729ecb5f5

test:
  secret_key_base: 41a64a7198c5cf5089d0efac77092a343380ba8c8361b0ffefbcef229a16ce1651f16abee7233f29ac899226805c1897b4f56ba7388b7c5a169c1083d9324c1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
